### ISSUE TITLE
One question about your solution

### ISSUE THREAD

**Issue by skmarlan** [PNergard/CMS75XmlResourcesTool#2]
Dear Per,

I am a software developer and I inherited the code of a web portal developed on EPiServer CMS (version 7.5) and the code of this application features the integration of XML Resouce Manager tool that was developed for you. It's going really well, however, it arises me a doubt and it is because we have done a rise in EPiServer CMS specifically version is version 9.12.0 Have you made some kind of functional test for this particular version?

On the other hand, could you clarify why into the table dbo.PlugIn I can find some records related to the values 'EPi.Plugins.XmlResourceManager' (AssemblyName field) or 'Nergard.EPi.Plugins.XmlResourceManager.Plugins.XmlResourceManager' (TypeName field)? Should I keep those records in the table or can be eliminated? If delete these records is the application still work?

Best regards,
David Bastos Lausín

**Comment by PNergard** [comment]
Shouldnt be a problem to upgrade.

You dont have to woryy about the tables because episerver handles it automatically.
